spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security_db
    username: postgres
    password: password2024
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create-drop  # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect



